name: Auto Build Deploy Client
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSHPASS
        run: |
          sshpass \
            -p ${{ secret.SSH_PASS }} \
              ssh \
                -o 'StrictHostKeyChecking no' \
                -p ${{ secret.SSH_PORT }} ${{ secret.SSH_USER }}@${{ secret.SSH_HOST }} \
                'cd /home/sel/selendra-app && git checkout main && git pull && npm i --force && npm run build && pm2 restart 1'
