name: Auto Build Deploy Client
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSHPASS
        run: |
          sshpass \
            -p ${{ secrets.SSH_PASS }} \
            ssh \
              -oProxyCommand="sshpass \
                -p ${{ secrets.JUMP_SSH_PASS }} \
                  ssh \
                    -W %h%p \
                    -o 'StrictHostKeyChecking no' \
                    ${{ secrets.JUMP_SSH_USER }}@${{ secrets.JUMP_SSH_HOST }}" \  
              -o 'StrictHostKeyChecking no' \
              -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              'cd /kmp/riverbase && git checkout main && git pull && cd client && npm i --force && npm run build && pm2 restart 26'
